"""Account insight storage.

Each account is one Markdown file under accounts/. Markdown is the format on
purpose: it diffs cleanly in git, so you and your team can review and add
insights via normal commits / PRs as you work the deal together.

The file has a fixed set of `## ` sections so the agent can read and update
specific parts (e.g. inject the value map) without disturbing your notes.
"""

import datetime
import re
from pathlib import Path

from . import framework

ACCOUNTS_DIR = Path(__file__).resolve().parent.parent / "accounts"

# Section headers, in display order.
SECTIONS = [
    "Snapshot",
    "Account Research",
    "Qualification (MEDDPICC)",
    "Current Data Landscape",
    "Pain Points",
    "MDM Value Mapping",
    "Discovery Notes",
    "Next Steps",
]


def slugify(name):
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "account"


def account_path(name):
    return ACCOUNTS_DIR / f"{slugify(name)}.md"


def today():
    return datetime.date.today().isoformat()


def new_brief(name, owner):
    """Return the Markdown for a fresh account brief."""
    meddpicc_lines = "\n".join(
        f"- **{field}:** _(tbd  {hint})_" for field, hint in framework.MEDDPICC
    )
    return f"""# Discovery Brief: {name}

## Snapshot
- **Account:** {name}
- **Stage:** Discovery
- **Owner:** {owner}
- **Created:** {today()}
- **Last updated:** {today()}

## Account Research
{framework.research_placeholder()}

## Qualification (MEDDPICC)
{meddpicc_lines}

## Current Data Landscape
_(Systems holding customer data, source-of-truth, volumes, integration style.)_

## Pain Points
_(One pain per line. The agent reads this section to map MDM value run
`python -m discovery_agent map "{name}"` after you fill it in.)_

## MDM Value Mapping
_(Auto-generated by the agent from Pain Points.)_

## Discovery Notes
_(Timestamped notes appended by `python -m discovery_agent note`.)_

## Next Steps
_(Owner + due date for each.)_
"""


def parse_sections(text):
    """Split brief text into {section_name: body} preserving order."""
    sections = {}
    current = None
    buffer = []
    for line in text.splitlines():
        m = re.match(r"^##\s+(.*)$", line)
        if m:
            if current is not None:
                sections[current] = "\n".join(buffer).strip("\n")
            current = m.group(1).strip()
            buffer = []
        elif current is not None:
            buffer.append(line)
    if current is not None:
        sections[current] = "\n".join(buffer).strip("\n")
    return sections


def render(name, sections):
    """Render a brief from a {section: body} dict in canonical order."""
    out = [f"# Discovery Brief: {name}", ""]
    for sec in SECTIONS:
        out.append(f"## {sec}")
        body = sections.get(sec, "").strip("\n")
        out.append(body if body else "_(empty)_")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def read(name):
    path = account_path(name)
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8")


def write(name, text):
    ACCOUNTS_DIR.mkdir(parents=True, exist_ok=True)
    account_path(name).write_text(text, encoding="utf-8")


def display_name(text, fallback):
    """Pull the human account name out of the Snapshot section."""
    m = re.search(r"^-\s+\*\*Account:\*\*\s+(.*)$", text, re.MULTILINE)
    return m.group(1).strip() if m else fallback


def get_field(text, field):
    """Read a `- **Field:** value` line; returns '' if missing/placeholder."""
    m = re.search(rf"^-\s+\*\*{re.escape(field)}:\*\*\s*(.*)$", text, re.MULTILINE)
    if not m:
        return ""
    val = m.group(1).strip()
    if val.startswith("_") or not val:
        return ""
    return val


def set_field(text, field, value):
    pattern = rf"^(-\s+\*\*{re.escape(field)}:\*\*).*$"
    # Use a function replacement so arbitrary user text (backslashes, \1, etc.)
    # is never interpreted as a regex backreference.
    value = (value or "").replace("\n", " ").strip()
    return re.sub(pattern, lambda m: f"{m.group(1)} {value}", text,
                  count=1, flags=re.MULTILINE)


SLUG_RE = re.compile(r"^[a-z0-9-]+$")


def find_by_slug(slug):
    """Safely resolve a slug to (display_name, text) or None. Prevents traversal."""
    if not slug or not SLUG_RE.match(slug):
        return None
    path = ACCOUNTS_DIR / f"{slug}.md"
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    return display_name(text, slug), text


def append_note(name, note):
    """Append a timestamped note to Discovery Notes. Returns new text or None."""
    text = read(name)
    if text is None:
        return None
    note = (note or "").strip()
    if not note:
        return text
    sections = parse_sections(text)
    display = display_name(text, name)
    entry = f"- **{today()}** {note}"
    existing = sections.get("Discovery Notes", "").strip()
    if existing.startswith("_(") or not existing:
        sections["Discovery Notes"] = entry
    else:
        sections["Discovery Notes"] = existing + "\n" + entry
    new_text = set_field(render(display, sections), "Last updated", today())
    write(name, new_text)
    return new_text


def apply_map(name):
    """Regenerate the MDM Value Mapping from Pain Points. Returns (text, signals)."""
    text = read(name)
    if text is None:
        return None, None
    sections = parse_sections(text)
    display = display_name(text, name)
    signals = framework.detect_signals(sections.get("Pain Points", ""))
    sections["MDM Value Mapping"] = framework.format_value_map(signals)
    new_text = set_field(render(display, sections), "Last updated", today())
    write(name, new_text)
    return new_text, signals


def save_brief(name, stage=None, owner=None, meddpicc=None, sections=None):
    """Update editable parts of a brief. Returns new text or None if missing."""
    text = read(name)
    if text is None:
        return None
    if sections:
        parsed = parse_sections(text)
        display = display_name(text, name)
        for key, body in sections.items():
            if key in SECTIONS:
                parsed[key] = body.strip("\n")
        text = render(display, parsed)
    if stage is not None:
        text = set_field(text, "Stage", stage)
    if owner is not None:
        text = set_field(text, "Owner", owner)
    if meddpicc:
        hints = dict(framework.MEDDPICC)
        for field, val in meddpicc.items():
            if field in hints:
                v = (val or "").strip()
                text = set_field(text, field, v if v else f"_(tbd  {hints[field]})_")
    text = set_field(text, "Last updated", today())
    write(name, text)
    return text


def list_accounts():
    """Return [{name, stage, file, meddpicc_filled, meddpicc_total}]."""
    if not ACCOUNTS_DIR.exists():
        return []
    rows = []
    for path in sorted(ACCOUNTS_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        name = display_name(text, path.stem)
        stage = get_field(text, "Stage") or "?"
        filled = sum(1 for f, _ in framework.MEDDPICC if get_field(text, f))
        rows.append({
            "name": name,
            "stage": stage,
            "file": path.name,
            "meddpicc_filled": filled,
            "meddpicc_total": len(framework.MEDDPICC),
        })
    return rows
